// packages/svelte/src/components/ImagePlaceholder.svelte
<script lang="ts">
export let hint: string;
export let width: number | undefined = undefined;
export let height: number | undefined = undefined;
</script>

<div
  class="image-placeholder"
  data-slide-placeholder={hint}
  data-placeholder-w={width}
  data-placeholder-h={height}
  role="img"
  aria-label={hint}
  style:width={width ? `${width}px` : '100%'}
  style:height={height ? `${height}px` : '100%'}
>
  <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM4 16l4-4 3 3 2-2 7 6M15.5 9.5h.01" /></svg>
  <span>Image</span>
  <strong>{hint}</strong>
  {#if width && height}<small>{width} × {height}</small>{/if}
</div>

<style>
  .image-placeholder {
    display: flex;
    position: relative;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    padding: 24px;
    overflow: hidden;
    color: rgb(90 90 100 / 70%);
    text-align: center;
    font-family: -apple-system, BlinkMacSystemFont, Inter, system-ui, sans-serif;
    flex-direction: column;
    gap: 8px;
    background: linear-gradient(135deg, rgb(120 120 130 / 6%), rgb(120 120 130 / 2%));
    border: 1px dashed rgb(120 120 130 / 35%);
    border-radius: 12px;
  }

  svg {
    width: 36px;
    fill: none;
    stroke: currentColor;
    stroke-width: 1.5;
  }

  span {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    opacity: 0.55;
  }

  strong {
    max-width: 85%;
    color: rgb(60 60 70 / 85%);
    font-size: 16px;
    font-weight: 500;
    line-height: 1.4;
  }

  small {
    font: 11px ui-monospace, SFMono-Regular, Menlo, monospace;
    opacity: 0.5;
  }
</style>

// packages/core/src/app/components/ImagePlaceholder.tsx
import type { CSSProperties, HTMLAttributes } from 'react';

export type ImagePlaceholderProps = {
  hint: string;
  width?: number;
  height?: number;
  style?: CSSProperties;
  className?: string;
} & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'style' | 'className'>;

export function ImagePlaceholder({
  hint,
  width,
  height,
  style,
  className,
  ...rest
}: ImagePlaceholderProps) {
  const dims = width && height ? `${width} × ${height}` : null;
  return (
    <div
      {...rest}
      data-slide-placeholder={hint}
      data-placeholder-w={width}
      data-placeholder-h={height}
      role="img"
      aria-label={hint}
      style={{
        position: 'relative',
        width: width ?? '100%',
        height: height ?? '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        gap: 14,
        border: '1px dashed rgba(120, 120, 130, 0.35)',
        borderRadius: 12,
        background:
          'linear-gradient(135deg, rgba(120,120,130,0.06) 0%, rgba(120,120,130,0.02) 50%, rgba(120,120,130,0.06) 100%)',
        color: 'rgba(90, 90, 100, 0.7)',
        fontFamily:
          '-apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", system-ui, sans-serif',
        textAlign: 'center',
        padding: 24,
        boxSizing: 'border-box',
        overflow: 'hidden',
        ...style,
      }}
      className={className}
    >
      <PlaceholderIcon />
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 6,
          maxWidth: '85%',
        }}
      >
        <span
          style={{
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            opacity: 0.55,
          }}
        >
          Image
        </span>
        <span
          style={{
            fontSize: 16,
            fontWeight: 500,
            lineHeight: 1.4,
            color: 'rgba(60, 60, 70, 0.85)',
          }}
        >
          {hint}
        </span>
        {dims && (
          <span
            style={{
              fontSize: 11,
              fontVariantNumeric: 'tabular-nums',
              fontFamily:
                'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
              opacity: 0.5,
              marginTop: 2,
            }}
          >
            {dims}
          </span>
        )}
      </div>
    </div>
  );
}

function PlaceholderIcon() {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 32 32"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ opacity: 0.55 }}
      aria-hidden
    >
      <rect x="4" y="6" width="24" height="20" rx="2.5" />
      <circle cx="11" cy="13" r="2" />
      <path d="M4 22l7-7 6 6 4-4 7 7" />
    </svg>
  );
}
